package AXi;

public class NodeNamer {
	
	public String getName(int id){
		switch (id){
		case 1:	return "Overlook";
		case 2: return "Valley";
		case 3: return "Lowlands";
		case 4: return "Golanta Clearing";
		case 5: return "Pangloss Rise";
		case 6: return "Speldan Clearcut";
		case 7: return "Danelon Passage";
		case 8: return "Umberglade Woods";
		case 9: return "Stonemist Castle";
		case 10: return "Rogue's Quarry";
		case 11: return "Aldon's Ledge";
		case 12:	return "Wildcreek Run";
		case 13:	return "Jerrifer's Slough";
		case 14:	return "Klovan Gully";
		case 15:	return "Langor Gulch";
		case 16:	return "Quentin Lake";
		case 17:	return "Mendon's Gap";
		case 18:	return "Anzalias Pass";
		case 19:	return "Ogrewatch Cut";
		case 20:	return "Veloka Slope";
		case 21:	return "Durios Gulch";
		case 22:	return "Bravost Escarpment";
		case 23:	return "Garrison";
		case 24:	return "Champion's Demense";
		case 25:	return "Redbriar";
		case 26:	return "Greenlake";
		case 27:	return "Ascension Bay";
		case 28:	return "Dawn's Eyrie";
		case 29:	return "The Spiritholme";
		case 30:	return "Woodhaven";
		case 31:	return "Askalion Hills";
		case 32:	return "Etheron Hills";
		case 33:	return "Dreaming Bay";
		case 34:	return "Victors's Lodge";
		case 35:	return "Greenbriar";
		case 36:	return "Bluelake";
		case 37:	return "Garrison";
		case 38:	return "Longview";
		case 39:	return "The Godsword";
		case 40:	return "Cliffside";
		case 41:	return "Shadaran Hills";
		case 42:	return "Redlake";
		case 43:	return "Hero's Lodge";
		case 44:	return "Dreadfall Bay";
		case 45:	return "Bluebriar";
		case 46:	return "Garrison";
		case 47:	return "Sunnyhill";
		case 48:	return "Faithleap";
		case 49:	return "Bluevale Refuge";
		case 50:	return "Bluewater Lowlands";
		case 51:	return "Astralholme";
		case 52:	return "Arah's Hope";
		case 53:	return "Greenvale Refuge";
		case 54:	return "Foghaven";
		case 55:	return "Redwater Lowlands";
		case 56:	return "The Titanpaw";
		case 57:	return "Cragtop";
		case 58:	return "Godslore";
		case 59:	return "Redvale Refuge";
		case 60:	return "Stargrove";
		case 61:	return "Greenwater Lowlands";
		case 62:	return "Temple of Lost Prayers";
		case 63:	return "Battle's Hollow";
		case 64:	return "Bauer's Estate";
		case 65:	return "Orchard Overlook";
		case 66:	return "Carver's Ascent";
		case 67:	return "Carver's Ascent";
		case 68:	return "Orchard Overlook";
		case 69:	return "Bauer's Estate";
		case 70:	return "Battle's Hollow";
		case 71:	return "Temple of Lost Prayers";
		case 72:	return "Carver's Ascent";
		case 73:	return "Orchard Overlook";
		case 74:	return "Bauer's Estate";
		case 75:	return "Battle's Hollow";
		case 76:	return "Temple of Lost Prayers";
		}	
		return null;
	}
	
	public String getIcon(int id){
		switch (id){
		case 1:	return "Keep.png";
		case 2: return "Keep.png";
		case 3: return "Keep.png";
		case 4: return "Camp.png";
		case 5: return "Camp.png";
		case 6: return "Camp.png";
		case 7: return "Camp.png";
		case 8: return "Camp.png";
		case 9: return "Castle.png";
		case 10: return "Camp.png";
		case 11: return "Tower.png";
		case 12:	return "Tower.png";
		case 13:	return "Tower.png";
		case 14:	return "Tower.png";
		case 15:	return "Tower.png";
		case 16:	return "Tower.png";
		case 17:	return "Tower.png";
		case 18:	return "Tower.png";
		case 19:	return "Tower.png";
		case 20:	return "Tower.png";
		case 21:	return "Tower.png";
		case 22:	return "Tower.png";
		case 23:	return "Keep.png";
		case 24:	return "Camp.png";
		case 25:	return "Tower.png";
		case 26:	return "Tower.png";
		case 27:	return "Keep.png";
		case 28:	return "Tower.png";
		case 29:	return "Camp.png";
		case 30:	return "Tower.png";
		case 31:	return "Keep.png";
		case 32:	return "Keep.png";
		case 33:	return "Keep.png";
		case 34:	return "Camp.png";
		case 35:	return "Tower.png";
		case 36:	return "Tower.png";
		case 37:	return "Keep.png";
		case 38:	return "Tower.png";
		case 39:	return "Camp.png";
		case 40:	return "Tower.png";
		case 41:	return "Keep.png";
		case 42:	return "Tower.png";
		case 43:	return "Camp.png";
		case 44:	return "Keep.png";
		case 45:	return "Tower.png";
		case 46:	return "Keep.png";
		case 47:	return "Tower.png";
		case 48:	return "Camp.png";
		case 49:	return "Camp.png";
		case 50:	return "Camp.png";
		case 51:	return "Camp.png";
		case 52:	return "Camp.png";
		case 53:	return "Camp.png";
		case 54:	return "Camp.png";
		case 55:	return "Camp.png";
		case 56:	return "Camp.png";
		case 57:	return "Tower.png";
		case 58:	return "Camp.png";
		case 59:	return "Camp.png";
		case 60:	return "Camp.png";
		case 61:	return "Camp.png";
		case 62:	return "TempleofLostPrayers.png";
		case 63:	return "BattlesHollow.png";
		case 64:	return "BauersEstate.png";
		case 65:	return "OrchardOverlook.png";
		case 66:	return "CarversAscent.png";
		case 67:	return "CarversAscent.png";
		case 68:	return "OrchardOverlook.png";
		case 69:	return "BauersEstate.png";
		case 70:	return "BattlesHollow.png";
		case 71:	return "TempleofLostPrayers.png";
		case 72:	return "CarversAscent.png";
		case 73:	return "OrchardOverlook.png";
		case 74:	return "BauersEstate.png";
		case 75:	return "BattlesHollow.png";
		case 76:	return "TempleofLostPrayers.png";
		}	
		return null;
	}

}
